In [1]:
import alpaca_trade_api as tradeapi
import requests
from dotenv import load_dotenv
import pandas as pd
import os

In [2]:
load_dotenv(verbose=True)

True

In [3]:
#alpaca_api_key = os.getenv("ALPACA_API_KEY")
#alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

alpaca_api_key = "PK2QATFJUTTJTLNCCC9E"
alpaca_secret_key = "OpvkG0g84P35EjDZlJZf0fMdJ4ksJiY6YwxNrN4d"
print(alpaca_api_key)

PK2QATFJUTTJTLNCCC9E

In [14]:
def calculate_sharpe_ratio(df):
    
    df_pct_change = df.pct_change()
    #daily_return
    sharpe_ratio = df_pct_change['close'].mean() / df_pct_change['close'].std()
    
    #annualized sharpe ratio
    return (252 ** 0.5) * sharpe_ratio

In [58]:
alpaca = tradeapi.REST(
    alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")

# Format current date as ISO format
start_date = pd.Timestamp("2011-05-01", tz="America/New_York").isoformat()
today = pd.Timestamp("2021-01-19", tz="America/New_York").isoformat()

# Set the tickers
tickers = ["SPY", "QQQ", "VTI",
           "SPBO", "JNK", "LQD",
           "IYR", "VNQ", "USRT",
           "PSP", "USO", "GLD",
           "MUB", "MUNI", "PZA",
           "VMBS", "MBB", "MBG",
           "TLT", "SCHO", "SHY"
           ]

# Set timeframe to '1D' for Alpaca API
timeframe = "1D"

# Get closing prices
df_ETFs = alpaca.get_barset(
    tickers,
    timeframe,
    start = start_date,
    end = today
).df

df_ETFs.to_csv("Resources/Data_ETFs_total.csv", encoding='utf-8', index=True)

In [41]:
sharpe_ratio_list = []
# for each of the tickers, we will calculate the sharpe ratio and store it in a list of dictionaries 
for ticker in tickers:
    sharpe_ratio = calculate_sharpe_ratio(df_ETFs[ticker])
    sharpe_ratio_list.append({"ticker": ticker, "sharpe_ratio" : sharpe_ratio})

# create a data frame with from the list
df_sharpe_ratio= pd.DataFrame(sharpe_ratio_list)
df_sharpe_ratio

   ticker  sharpe_ratio
0     SPY      0.689446
1     QQQ      0.758361
2     VTI      0.691611
3    SPBO      0.424475
4     JNK      0.306122
5     LQD      0.335085
6     IYR      0.258411
7     VNQ      0.258461
8    USRT      0.172504
9     PSP      0.162776
10    USO      0.245192
11    GLD      0.168871
12    MUB      0.305497
13   MUNI      0.311248
14    PZA      0.307376
15   VMBS      0.220149
16    MBB      0.148838
17    MBG     -0.093436
18    TLT      0.420164
19   SCHO      0.268354
20    SHY      0.311147

In [22]:
df_ETFs.head()

                             AAPL                                       \
                             open      high      low   close    volume
2020-01-02 05:00:00+00:00  296.24  300.6000  295.190  300.58  30589026
2020-01-03 05:00:00+00:00  297.15  300.5800  296.500  297.38  31609363
2020-01-06 05:00:00+00:00  293.79  299.9600  292.750  299.78  27487207
2020-01-07 05:00:00+00:00  299.84  300.9000  297.480  298.27  24353387
2020-01-08 05:00:00+00:00  297.16  304.4399  297.156  303.15  28984028

                              AMZN                                          \
                              open       high        low    close   volume
2020-01-02 05:00:00+00:00  1874.79  1898.0000  1864.1500  1897.71  3583611
2020-01-03 05:00:00+00:00  1864.50  1886.1965  1864.5000  1874.93  3293469
2020-01-06 05:00:00+00:00  1860.00  1903.6900  1860.0000  1903.33  3598872
2020-01-07 05:00:00+00:00  1904.50  1913.8900  1892.0433  1906.86  3638680
2020-01-08 05:00:00+00:00  1898.68  1910.9999  1886.4448  1892.09  3032612

                           ...    VNQ                                    \
                           ...   open     high      low  close   volume
2020-01-02 05:00:00+00:00  ...  93.19  93.2399  91.1000  91.53  4840634
2020-01-03 05:00:00+00:00  ...  91.15  92.4600  91.0300  92.28  4537365
2020-01-06 05:00:00+00:00  ...  92.17  92.7100  91.8699  92.36  4189297
2020-01-07 05:00:00+00:00  ...  92.18  92.1800  90.8545  91.28  6043125
2020-01-08 05:00:00+00:00  ...  91.39  91.8100  91.1400  91.60  6309497

                              VTI
                             open     high       low   close   volume
2020-01-02 05:00:00+00:00  164.68  164.970  163.7800  164.97  3324174
2020-01-03 05:00:00+00:00  163.29  164.470  163.0100  163.92  3529079
2020-01-06 05:00:00+00:00  162.92  164.520  162.8300  164.51  3161370
2020-01-07 05:00:00+00:00  164.27  164.455  163.7811  164.09  2422948
2020-01-08 05:00:00+00:00  164.34  165.545  164.1500  164.89  3318287

[5 rows x 120 columns]

In [69]:
# Set the tickers
tickers = ["QQQ", 
           "LQD",
           "VNQ",
           "USO", 
           "PZA",
           "VMBS",
           "TLT"
           ]

# Set timeframe to '1D' for Alpaca API
timeframe = "1D"

# Get closing prices
df_ETFs = alpaca.get_barset(
    tickers,
    timeframe,
    start = start_date,
    end = today
).df
df_ETFs1 = df_ETFs.dropna()
df_ETFs1.to_csv("Resources/Data_ETFs_to_use.csv", encoding='utf-8', index=True)

In [70]:
short_window = 50
long_window = 200

df_closing = pd.DataFrame()

df_closing["QQQ_close"] = df_ETFs1["QQQ"]["close"]
df_closing["QQQ_return"] = df_ETFs1["QQQ"]["close"].pct_change()
df_closing["QQQ_SMA50"] = df_closing["QQQ_close"].rolling(window=short_window).mean()
df_closing["QQQ_SMA200"] = df_closing["QQQ_close"].rolling(window=long_window).mean()
df_closing["QQQ_Vol"] = df_ETFs1["QQQ"]["volume"]

df_closing["LQD_close"] = df_ETFs1["LQD"]["close"]
df_closing["LQD_return"] = df_ETFs1["LQD"]["close"].pct_change()
df_closing["LQD_SMA50"] = df_closing["LQD_close"].rolling(window=short_window).mean()
df_closing["LQD_SMA200"] = df_closing["LQD_close"].rolling(window=long_window).mean()
df_closing["LQD_Vol"] = df_ETFs1["LQD"]["volume"]

df_closing["VNQ_close"] = df_ETFs1["VNQ"]["close"]
df_closing["VNQ_return"] = df_ETFs1["VNQ"]["close"].pct_change()
df_closing["VNQ_SMA50"] = df_closing["VNQ_close"].rolling(window=short_window).mean()
df_closing["VNQ_SMA200"] = df_closing["VNQ_close"].rolling(window=long_window).mean()
df_closing["VNQ_Vol"] = df_ETFs1["VNQ"]["volume"]


df_closing["USO_close"] = df_ETFs1["USO"]["close"]
df_closing["USO_return"] = df_ETFs1["USO"]["close"].pct_change()
df_closing["USO_SMA50"] = df_closing["USO_close"].rolling(window=short_window).mean()
df_closing["USO_SMA200"] = df_closing["USO_close"].rolling(window=long_window).mean()
df_closing["USO_Vol"] = df_ETFs1["USO"]["volume"]

df_closing["PZA_close"] = df_ETFs1["PZA"]["close"]
df_closing["PZA_return"] = df_ETFs1["PZA"]["close"].pct_change()
df_closing["PZA_SMA50"] = df_closing["PZA_close"].rolling(window=short_window).mean()
df_closing["PZA_SMA200"] = df_closing["PZA_close"].rolling(window=long_window).mean()
df_closing["PZA_Vol"] = df_ETFs1["PZA"]["volume"]

df_closing["VMBS_close"] = df_ETFs1["VMBS"]["close"]
df_closing["VMBS_return"] = df_ETFs1["VMBS"]["close"].pct_change()
df_closing["VMBS_SMA50"] = df_closing["VMBS_close"].rolling(window=short_window).mean()
df_closing["VMBS_SMA200"] = df_closing["VMBS_close"].rolling(window=long_window).mean()
df_closing["VMBS_Vol"] = df_ETFs1["VMBS"]["volume"]

df_closing["TLT_close"] = df_ETFs1["TLT"]["close"]
df_closing["TLT_return"] = df_ETFs1["TLT"]["close"].pct_change()
df_closing["TLT_SMA50"] = df_ETFs1["TLT_close"].rolling(window=short_window).mean()
df_closing["TLT_SMA200"] = df_ETFs1["TLT_close"].rolling(window=long_window).mean()
df_closing["TLT_Vol"] = df_ETFs1["TLT"]["volume"]

df_closing.index = df_closing.index.date
                                   
# Output the data to CSV
df_closing.to_csv("Resources/Data_ETFs_model_use.csv", encoding='utf-8', index=True)

KeyError: 'QQQ_close'

In [60]:
df_closing

,QQQ_close,QQQ_return,QQQ_SMA50,QQQ_SMA200,QQQ_Vol,LQD_close,LQD_return,LQD_SMA50,LQD_SMA200,LQD_Vol,...,VMBS_close,VMBS_return,VMBS_SMA50,VMBS_SMA200,VMBS_Vol,TLT_close,TLT_return,TLT_SMA50,TLT_SMA200,TLT_Vol
2011-05-02,58.9924,NaN,NaN,NaN,44312089,110.31,NaN,NaN,NaN,1374460.0,...,50.7700,NaN,NaN,NaN,9903.0,93.6300,NaN,NaN,NaN,4389946.0
2011-05-03,58.6900,-0.005126,NaN,NaN,30746589,110.25,-0.000544,NaN,NaN,648982.0,...,50.8590,0.001753,NaN,NaN,3887.0,94.1500,0.005554,NaN,NaN,5952435.0
2011-05-04,58.6000,-0.001533,NaN,NaN,48174869,110.40,0.001361,NaN,NaN,656364.0,...,50.8176,-0.000814,NaN,NaN,3146.0,94.5900,0.004673,NaN,NaN,6600138.0
2011-05-05,58.2800,-0.005461,NaN,NaN,60501065,110.79,0.003533,NaN,NaN,761126.0,...,50.9880,0.003353,NaN,NaN,1731.0,95.4600,0.009198,NaN,NaN,7990952.0
2011-05-06,58.4800,0.003432,NaN,NaN,59986642,110.77,-0.000181,NaN,NaN,830286.0,...,51.0400,0.001020,NaN,NaN,11474.0,95.0701,-0.004084,NaN,NaN,8701719.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-01-12,313.9800,-0.001050,300.5668,264.18496,27010140,135.47,0.001849,136.7254,NaN,13240352.0,...,53.9100,-0.001852,54.076468,54.280389,2122541.0,150.9700,-0.000596,157.352234,NaN,12279489.0
2021-01-13,316.0000,0.006434,301.4926,264.80441,19895283,136.52,0.007751,136.7812,NaN,15276377.0,...,53.9700,0.001113,54.073568,54.277439,5885304.0,152.6500,0.011128,157.253634,NaN,10978139.0
2021-01-14,314.2500,-0.005538,302.3766,265.42336,21959596,135.96,-0.004102,136.8210,NaN,20916224.0,...,53.9900,0.000371,54.071568,54.274739,1672910.0,151.2400,-0.009237,157.107234,NaN,13452750.0
2021-01-15,311.9000,-0.007478,303.1220,266.07091,31873279,136.14,0.001324,136.8626,NaN,11651363.0,...,54.0300,0.000741,54.069568,54.273389,2218101.0,151.8600,0.004099,156.990434,NaN,9383714.0
2021-01-19,316.4300,0.014524,303.7136,266.72296,21607968,136.38,0.001763,136.8682,NaN,11848319.0,...,54.0100,-0.000370,54.066168,54.271339,1616045.0,152.3600,0.003293,156.816434,NaN,7938596.0

In [62]:
df_closing1 = df_closing.dropna()
df_closing1

,QQQ_close,QQQ_return,QQQ_SMA50,QQQ_SMA200,QQQ_Vol,LQD_close,LQD_return,LQD_SMA50,LQD_SMA200,LQD_Vol,...,VMBS_close,VMBS_return,VMBS_SMA50,VMBS_SMA200,VMBS_Vol,TLT_close,TLT_return,TLT_SMA50,TLT_SMA200,TLT_Vol
2012-02-14,63.210,0.002856,56.5943,55.642217,33059444,116.55,0.001289,114.136202,112.460410,1746454.0,...,52.060,0.001154,52.021854,51.753993,35210.0,117.750,0.005207,118.76020,109.394110,7417042.0
2012-02-15,62.750,-0.007277,56.8009,55.661005,71839964,116.42,-0.001115,114.234652,112.490960,885907.0,...,52.090,0.000576,52.029464,51.760593,45862.0,117.550,-0.001699,118.73780,109.513710,6690835.0
2012-02-16,63.620,0.013865,57.0133,55.685655,63607526,116.27,-0.001288,114.313652,112.521060,1581477.0,...,52.060,-0.000576,52.033944,51.766598,19284.0,116.610,-0.007997,118.70120,109.626010,8527190.0
2012-02-17,63.430,-0.002986,57.1403,55.709805,37422734,116.01,-0.002236,114.399252,112.549110,1631797.0,...,52.040,-0.000384,52.037004,51.772710,14079.0,116.600,-0.000086,118.68780,109.736060,5991144.0
2012-02-21,63.610,0.002838,57.3555,55.736455,34755703,115.84,-0.001465,114.468052,112.574360,1779776.0,...,52.005,-0.000673,52.035904,51.777795,59420.0,115.290,-0.011235,118.63980,109.835210,6985597.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-08-06,274.585,0.012818,251.4717,220.077725,25188339,139.13,0.003896,135.130700,129.508522,13775405.0,...,54.360,0.000368,54.398580,53.809968,1010600.0,171.020,0.005438,164.82055,153.761978,7947815.0
2020-08-07,271.500,-0.011235,252.3057,220.475875,42625085,138.79,-0.002444,135.282800,129.567172,12859164.0,...,54.460,0.001840,54.397180,53.816618,1389988.0,169.890,-0.006607,164.96965,153.914738,7492566.0
2020-08-10,270.280,-0.004494,253.0537,220.866175,33617437,138.47,-0.002306,135.411800,129.623772,11430826.0,...,54.520,0.001102,54.396580,53.823368,955359.0,169.100,-0.004650,165.08185,154.062888,6107009.0
2020-08-11,265.210,-0.018758,253.6743,221.221825,39713826,137.59,-0.006355,135.532200,129.674622,24611821.0,...,54.335,-0.003393,54.392880,53.829343,1007493.0,167.105,-0.011798,165.17875,154.202438,16853768.0
2020-08-12,271.930,0.025338,254.3995,221.603425,35733309,137.25,-0.002471,135.635600,129.724922,20158956.0,...,54.340,0.000092,54.388680,53.835293,2410095.0,165.610,-0.008946,165.25795,154.337988,10390698.0

In [51]:
# Construct training start and end dates
training_start = df_closing1.index.min().strftime(format= '%Y-%m-%d')
training_end = '2019-09-14'

# Construct testing start and end dates
testing_start =  '2019-09-15'
testing_end = df_closing1.index.max().strftime(format= '%Y-%m-%d')

# Print training and testing start/end dates
print(f"Training Start: {training_start}")
print(f"Training End: {training_end}")
print(f"Testing Start: {testing_start}")
print(f"Testing End: {testing_end}")

Training Start: 2019-12-02
Training End: 2019-09-14
Testing Start: 2019-09-15
Testing End: 2021-01-19

In [ ]:
# Set x variable list of features
x_var_list = ['crossover_signal', 'vol_trend_signal', 'bollinger_signal']

# Filter by x-variable list
trading_signals_df[x_var_list].tail()